travis:
  secure:
    BINSTAR_TOKEN: 3BYdo4WOqlhPHRdXw64RDO17nRG38tyb+dAjqBvmxrwhZr6AWb9teWAHzOiXoyb6vjzUhRlScZOtmexwEvzFI0N9XTpjw3P3QU5mRugdSKkZZNHvKE+5g6VAR/4FIThm2A/7+17Jrm38Iz7fFnQHc+sIX9cSaSCxr+zroxspH2QzUZwf6kByw+5DQcdz2pjo/LgyrW3tYDRZLaj95mNQYhlSPydJ7HGajxBZwDH/fSQRjaJ5Y6RFH8c9rIt9xbmuwc/UBq6Bj0hvumf1KGIR5WR9wlP0q3r4cSiEADicRPNkF8kwRogot9OlKPZSarLY+VTyuR0W/ZjEkDDbhSwwHT19c61lsPtrgrxIlBmbjx2T3mOiS1C7HjTtAtXD7dpuzBcHCvBFFS7LLJ5jZKTutZJABVA6mVHFgxg4HbJ43A5jaQw9PeOFs+EcEQUfWkaiz9b2vGh70+ia7K7mV27vOBOAQxrjJO3+3SNGvCxbn5srWKW1szRH3D/WwCngCn3dllpyH62GTKtpF9ttUxTe6+6Q/xeJEjs0n/P3FGJhemQbPhD8dgRQjVNs6RmFS/SSXyX6t2naxieUxGS6XVdZioJAKyL7vbQnSIZzpeNH9aT0zInTrIlJBCpRMw0rY2tSwWa3GizFBTOPpg6e34jwcEoNTRmxazsKCpmL41JRuqU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
